project:
  type: website
  preview:
    port: 4200

website:
  favicon: _images/trebleclef.jpg

metadata-files:
  - _website.yml

format:
  html:
    include-after-body: custom.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
  pdf:
    documentclass: article
    filters:
      - filters/tables.lua
      - filters/titlered.lua
      - filters/float-right.lua
    template-partials:
      - tex/before-body.tex
    include-in-header:
      - text: |
          \usepackage{tex/musicschedule}
      
execute:
  echo: false
