project:
  type: website
  preview:
    port: 4200
  execute-dir: file

website:
  favicon: images/trebleclef.png

metadata-files:
  - _website.yml

format:
  html:
    include-after-body: custom.html
    theme:
      - cosmo
      - brand
    filters:
      - filters/links-in-new-tab.lua
    css: styles.css
    toc: true
    toc-depth: 4
      
execute:
  echo: false
