---
title: "Music Schedule: Advent-Christmas 2025"
---


## litweek

| | | |
|---|---|---|
|| **Processional:** | 577 – \href{https://www.youtube.com/watch?v=EBHr3p3xHCY |
|| **Responsorial Psalm:** | \href{https://youtu.be/4yPHj2DFoC4?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/6JGogB_Mb-I?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 443 – \href{https://www.youtube.com/watch?v=Op9Yyh_M4dk |
|| **Communion:** | 397 – \href{https://www.youtube.com/watch?v=YQQjF8pTBV4 |
|| **Recessional:** | 766 – \href{https://www.youtube.com/watch?v=jLBQEUauY-I |


## litweek

| | | |
|---|---|---|
|| **Processional:** | 418 – \href{https://www.youtube.com/watch?v=YvvEQkspJxY |
|| **Responsorial Psalm:** | \href{https://youtu.be/KlaXFWpN7n4?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/EFvpHsLDBOU?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 421 – \href{https://www.youtube.com/watch?v=ldb56S3ZQ7M |
|| **Communion:** | 397 – \href{https://www.youtube.com/watch?v=YQQjF8pTBV4 |
|| **Recessional:** | 409 – \href{https://www.youtube.com/watch?v=YGjPQ5yitcM |


## Solemnity of the Immaculate Conception

| | | |
|---|---|---|
|| **Processional:** | 886 – \href{https://www.youtube.com/watch?v=7fascMNAJCc |
|| **Responsorial Psalm:** | \href{https://youtu.be/Bk_8VhRGweU?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/F2YKiu3hbEY?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 875 – \href{https://www.youtube.com/watch?v=hvaDKdZ20bo |
|| **Offertory:** | 100 – \href{https://www.youtube.com/watch?v=4ZpjtGWWTIY |
|| **Communion:** | 876 – \href{https://www.youtube.com/watch?v=_4U8gIN944o |
|| **Communion:** | 100 – \href{https://www.youtube.com/watch?v=4ZpjtGWWTIY |
|| **Recessional:** | 458 – \href{https://www.youtube.com/watch?v=CIyxIu9Wkbk |


## litweek

| | | |
|---|---|---|
|| **Processional:** | 404 – \href{https://www.youtube.com/watch?v=0YO0bCK_y_E |
|| **Responsorial Psalm:** | \href{https://youtu.be/WOw1ZGgmceM?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |


## litweek

| | | |
|---|---|---|
|| **Processional:** | 401 – \href{https://www.youtube.com/watch?v=RT1qMElAzas |
|| **Responsorial Psalm:** | \href{https://youtu.be/eTn_fK_16_4?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/mDRuiP8oB8s?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 395 – \href{https://www.youtube.com/watch?v=wZdPSU98tmQ |
|| **Communion:** | 414 – \href{https://www.youtube.com/watch?v=IErDZHDeoZc |
|| **Recessional:** | 572 – \href{https://www.youtube.com/watch?v=eqLjN27r6fI |


## Christmas

| | | |
|---|---|---|
|| **Processional:** | 439 – \href{https://www.youtube.com/watch?v=epvG0Q2-D6E |
|| **Responsorial Psalm:** | 70 – \href{https://www.youtube.com/watch?v=YUDFGKBAzUc |
|| **Gospel Acclamation:** | \href{https://youtu.be/KxUt7PyXNYk?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |


## Holy Family of Jesus

| | | |
|---|---|---|
|| **Processional:** | 438 – \href{https://www.youtube.com/watch?v=MQHKpSyWN78 |
|| **Responsorial Psalm:** | \href{https://youtu.be/4gjqxJ_eL-I?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/hzF6qrivXl8?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 436 – \href{https://www.youtube.com/watch?v=j88dBFX0FDg |
|| **Communion:** | 455 – \href{https://www.youtube.com/watch?v=TT3cfXd3Shk |
|| **Recessional:** | 430 – \href{https://www.youtube.com/watch?v=NQGUisGUyrI |


## Solemnity of Mary

| | | |
|---|---|---|
|| **Processional:** | 457 – \href{https://www.youtube.com/watch?v=NedM6uN8TUA |
|| **Responsorial Psalm:** | \href{https://youtu.be/LcqkBimDhjs?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/JuH7sw1sobE?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 448 – \href{https://www.youtube.com/watch?v=Wg0UpWtpM1I |
|| **Communion:** | 451 – \href{https://www.youtube.com/watch?v=h_RRlNtAlKg |
|| **Recessional:** | 458 – \href{https://www.youtube.com/watch?v=CIyxIu9Wkbk |


## Epiphany of the Lord

| | | |
|---|---|---|
|| **Processional:** | 459 – \href{https://www.youtube.com/watch?v=I4cg0aOczWo |
|| **Responsorial Psalm:** | \href{https://youtu.be/5poRq9YtiIs?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/HiKwEUIipX8?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 463 – \href{https://www.youtube.com/watch?v=_c1RfmfVBL8 |
|| **Communion:** | 460 – \href{https://www.youtube.com/watch?v=HVfUGWAJtGI |
|| **Recessional:** | 461 – \href{https://www.youtube.com/watch?v=1_ifsk8loik |


## Baptism of the Lord

| | | |
|---|---|---|
|| **Processional:** | 467 – \href{https://www.youtube.com/watch?v=CUZwA0zgN9A |
|| **Responsorial Psalm:** | \href{https://youtu.be/UaV7slHh658?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Gospel Acclamation:** | \href{https://youtu.be/D4l2yvw-2z4?list=PL1_lMtcpfrcloo19ceGJAEXPuXK2LS4os |
|| **Offertory:** | 440 – \href{https://www.youtube.com/watch?v=xybA16UklwQ |
|| **Communion:** | 13 – \href{https://www.youtube.com/watch?v=hq-_otZmma0 |
|| **Communion:** | 423 – \href{https://www.youtube.com/watch?v=Op9Yyh_M4dk |
|| **Recessional:** | 428 – \href{https://www.youtube.com/watch?v=FmHd96ZA6gY |
