---
title: Mass of St. Dymphna
author: Barbara Gallagher
subtitle: For Fr. Ryszard Kolodziej and Basilica Shrine of St. Mary, Wilmington, NC
tbl-cap-location: bottom
---

Fr. Ryszard has asked us to learn and starting singing the *Mass of St. Dymphna*. We will begin introducing these Mass parts to the congregation starting **Lent 2026**, which begins on Wednesday, February 18.

Audio samples are below. Download a copy of the cantor sheet [here](images/MassOfStDymphna_melody.pdf).

We will start by introducing the Holy, Memorial Acclamation, and Great Amen. We will then add the Lamb of God and, after Lent, the Gloria.

::: {.callout-important title="Cantors and choir members: Please start learning these now!"}
As vocal leaders, you will need to comfortably lead these parts until the congregation learns them well enough to sing. We will learn them together at choir and cantor rehearsals between now and then. (Note that we will sing all of them faster than performed here.)
:::


+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
|                                 | [Recording]{.red .large}                                               | [Melody only]{.red .large}                                                    |
+=================================+:======================================================================:+:=============================================================================:+
| [Gloria]{.red .large}           | <audio controls="">                                                    | <audio controls="">                                                           |
|                                 |     <source src="./audio/st-dymphna-gloria.mp3" type="audio/wav"/>     |     <source src="./audio/st-dymphna-gloria-melody.m4a" type="audio/wav"/ >    |
|                                 | </audio> <br>                                                          | </audio>                                                                      |
+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| [Holy, Holy, Holy]{.red .large} | <audio controls="">                                                    | <audio controls="">                                                           |
|                                 |     <source src="./audio/st-dymphna-holy.mp3" type="audio/wav"/>       |     <source src="./audio/st-dymphna-holy-melody.m4a" type="audio/wav"/ >      |
|                                 | </audio> <br>                                                          | </audio>                                                                      |
+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| [Memorial]{.red .large}         | <audio controls="">                                                    | <audio controls="">                                                           |
| [Acclamation]{.red .large}      |     <source src="./audio/st-dymphna-memaccA.mp3" type="audio/wav"/>    |     <source src="./audio/st-dymphna-memaccA-melody.m4a" type="audio/wav"/ >   |
|                                 | </audio> <br>                                                          | </audio>                                                                      |
+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| [Amen]{.red .large}             | <audio controls="">                                                    | <audio controls="">                                                           |
|                                 |     <source src="./audio/st-dymphna-amen.mp3" type="audio/wav"/>       |     <source src="./audio/st-dymphna-amen-melody.m4a" type="audio/wav"/ >      |
|                                 | </audio> <br>                                                          | </audio>                                                                      |
+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| [Lamb of God]{.red .large}      | <audio controls="">                                                    | <audio controls="">                                                           |
|                                 |     <source src="./audio/st-dymphna-lambofgod.mp3" type="audio/wav"/>  |     <source src="./audio/st-dymphna-lambofgod-melody.m4a" type="audio/wav"/ > |
|                                 | </audio> <br>                                                          | </audio>                                                                      |
+---------------------------------+------------------------------------------------------------------------+-------------------------------------------------------------------------------+

: Recordings courtesy of the [Wilmington Choral Society](https://www.wilmingtonchoralsociety.com/), directed by Byron Marshall with accompanists Sheryl Tjon and Luis Barragan. Melodies are digitally generated.
