---
title: "Weddings at St. Egbert's"
subtitle: Guidance for liturgical music selection
---

Congratulations on your big day! We wish you a lifetime of blessings and happiness.

For Catholics, weddings are a *liturgical celebration* of the *sacrament of Holy Matrimony* (marriage), a sacrifice of two people becoming one in God. What is liturgy, you ask? Liturgy is at the heart of what the church does: it is our public worship of God, creatures worshipping our creator. And what is worship? It is giving thanks and honor to God that is due to him for all he has given to us. It is our expression of honor, acknowledgement, and respect to and for God because he is greater than us in all ways. Everything about the wedding liturgy, including the music, is about your worship of God and God alone. For this reason, the Church prohibits popular music of any kind within the liturgy. Liturgical music must be deliberate, appropriate, and "correspond to the spirit of the liturgical celebration itself" ([*Instruction on Music in the Liturgy (Musicam sacram)*](https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_instr_19670305_musicam-sacram_en.html), 9). Suitable music options are provided below to help you plan your wedding liturgy.

> "The marriage covenant, by which a man and a woman form with each other an intimate communion of life and love, has been founded and endowed with its own special laws by the Creator."  
> [*On the Church in the Modern World (Gaudium et Spes*)](https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651207_gaudium-et-spes_en.html), 48

### Processional and Recessional Instrumentals

Choose one for the entrance of mothers, the bridal party, and the bride. Alternatively, separate pieces can be used for each entrance, if desired:

* Canon in D Major (Pachelbel)

* Bist du Bei Mir (Bach)
	
*	Overture from Royal Fireworks Suite (Handel)

* Prelude to Te Deum — organ and trumpet (Charpentier)
* Prelude to Te Deum — organ only

* Trumpet Tune — organ and trumpet (Purcell/Clarke)
* Trumpet Tune — organ only

* Trumpet Tune in D (Johnson)
* Trumpet Tune in D — organ only

* Trumpet Voluntary — organ and trumpet (Clarke)
* Trumpet Voluntary — organ only


### Responsorial Psalm

Choose one psalm:

	Psalm 25: To You, O Lord (Soper) — all verses

	Psalm 103: The Lord is Kind and Merciful (Haas) — all verses

	Psalm 145: I Will Praise Your Name (Haas; BB, GC) — all verses
		For all verses: https://www.youtube.com/watch?v=VoJmPNZTO84


### Hymns

If you are having a full Mass, choose one for the presentation of the gifts and one for communion:

* All Praise and Glad Thanksgiving or
* O God, Almighty Father (GOTT VATER SEI GEPRIESEN; BB, WPS)

* God Is Love (ABBOT’S LEIGH; BB)

* God, We Praise You (NETTLETON; BB)

* God, Who Created Hearts to Love (LASST UNS ERFREUEN; BB)

* Hear Us Now, Our God and Father (HYFRYDOL, BB)

* Love Divine, All Loves Excelling (HYFRYDOL; BB, WPS)

* O God Beyond All Praising (THAXTED; BB)

* Praise, My Soul, the King of Heaven (LAUDA ANIMA; BB, WSP)

Gifts

	God, in the Planning and Purpose of Life (SLANE; WPS)

	No Greater Love (Joncas; WPS)

	Not for Tongues of Heaven’s Angels (WPS)

	When Love is Found (O WALY WALY; WPS)


Communion

	One Love Released (Frenzel and Keil; BB)

	Ubi Caritas (chant; WPS) 

	Ubi Caritas (Hurd; BB) — vs. 1,2,3,5

	Ubi Caritas (Taize style; WPS)

	Take and Eat (Joncas; GC, WPS) — end with vs. 6
	
	The Supper of the Lord (Rosania; BB)

	When We Eat This Bread (Joncas; BB) — vs. 1,2,5


Recessional

	Allegro Moderato (from Water Music) (Handel)

	Hornpipe (from Water Music) (Handel)

	Ode to Joy (Beethoven)

	Psalm 19: The Heaven’s Declare the Glory of God (Marcello)

	Rondeau (from Symphony of Fanfares) (Mouret)

	The Rejoicing (from Fireworks Suite) (Handel)

	Trumpet Voluntary — organ and trumpet (Stanley)
	Trumpet Voluntary — organ only


