# =============================================================================
# author: mgrossi
# date:   04 March 2026
#
# This script reads `--infile, -i` CSV file and prints the cantor schedule to
# the screen along with tallies for each cantor, optionally filtered by month
# using `--month, -m`. Input file defaults to `[pwd]/calendars/cantors.csv`
# generated by `cantors.py`. If `--outfile, -o` is passed, the cantor schedule
# is written to file as well. This is an abbreviated version of the full CSV
# that can be shared with cantors without unnecessary data columns.
#
# To execute in terminal:
#
#     python cantor-counts.py --month 3
#
# or
#
#     python cantor-counts.py --month 3 --outfile schedule.csv
#
# =============================================================================
# Packages
from pathlib import Path
import pandas as pd
import argparse
import calendar
import os.path

# -----------------------------------------------------------------------------
# Local development

# class Args:
#     def __init__(self, infile='calendars/cantors.csv', outfile=None, month=None):
#         self.start = infile
#         self.end = outfile
#         self.month = month
# args = Args()

# -----------------------------------------------------------------------------
# Command line execution

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Function control parameters.',
        prog='cantor-counts',
        usage='%(prog)s [arguments]')
    parser.add_argument('-i', '--infile', nargs='?', type=str, 
                        default='calendars/cantors.csv',
                        help='Name and directory of csv file to read. Default to "[pwd]/calendars/cantors.csv"')
    parser.add_argument('-o', '--outfile', nargs='?', type=str, 
                        default=None,
                        help='Name and directory of csv file to write, if desired. Default to None')
    parser.add_argument('-m', '--month', type=int, default=None,
                        help='Optional month filter')
    return parser.parse_args()

args = parse_args()

# -----------------------------------------------------------------------------
# Main program

def main():
    # Project home directory
    PROJECT_ROOT = Path(__file__).resolve().parent.parent

    # Load the data
    df = pd.read_csv(args.infile, parse_dates=['start'])

    # Filter
    if args.month:
        df = df[df['start'].dt.month==args.month]

    # Display the results
    if args.month:
        print(f'\nCANTOR SCHEDULE FOR {calendar.month_name[args.month].upper()}:\n')
    else:
        print('\nCANTOR SCHEDULE:\n')

    print(df[['Date', 'Mass Time', 'Name']].set_index('Date'))

    print('\n')
    if args.month:
        print(f'TALLIES FOR {calendar.month_name[args.month].upper()}:\n')
    else:
        print('TALLIES:\n')
    print(df.value_counts('Name'))
    print('\n')

    # Save, if desired
    if args.outfile:
        df[['Date', 'Mass Time', 'Name']].set_index('Date').to_csv(os.path.join(PROJECT_ROOT, args.outfile))
        print(f'Cantor schedule saved to file: {os.path.join(PROJECT_ROOT, args.outfile)}')

if __name__ == '__main__':
    main()