"""
cantor-counts.py
================
Reads a cantor schedule CSV and prints the schedule and per-cantor tallies,
optionally filtered by month.

Usage
-----
    python cantor-counts.py --month 3
    python cantor-counts.py --month 3 --outfile schedule.csv

Arguments
---------
    -i, --infile   CSV file to read (default: calendars/cantors.csv)
    -o, --outfile  CSV file to write (optional)
    -m, --month    Month number to filter by (optional)

Input
-----
    CSV file generated by cantors.py, expected columns:
    start, Date, Mass Time, Name

Author: mgrossi
"""

# =============================================================================

# This script reads `--infile, -i` CSV file and prints the cantor schedule to
# the screen along with tallies for each cantor, optionally filtered by month
# using `--month, -m`. Input file defaults to `[pwd]/calendars/cantors.csv`
# generated by `cantors.py`. If `--outfile, -o` is passed, the cantor schedule
# is written to file as well. This is an abbreviated version of the full CSV
# that can be shared with cantors without unnecessary data columns.

# =============================================================================
# Packages
from pathlib import Path
import pandas as pd
import argparse
import calendar
import os.path

# -----------------------------------------------------------------------------
# Local development

# class Args:
#     def __init__(self, infile='calendars/cantors.csv', outfile=None, month=None):
#         self.start = infile
#         self.end = outfile
#         self.month = month
# args = Args()

# -----------------------------------------------------------------------------
# Command line execution

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        prog='cantor-counts',
        usage='%(prog)s [arguments]',
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-i', '--infile', nargs='?', type=str, 
                        default='calendars/cantors.csv',
                        help='Name and directory of csv file to read. Default: "[pwd]/calendars/cantors.csv"')
    parser.add_argument('-o', '--outfile', nargs='?', type=str, 
                        default=None,
                        help='Name and directory of csv file to write, if desired. Default: None for no saving.')
    parser.add_argument('-m', '--month', type=int, default=None,
                        help='Optional month to filter by')
    return parser.parse_args()

args = parse_args()

# -----------------------------------------------------------------------------
# Main program

def main():
    # Quarto project home directory
    PROJECT_ROOT = Path(__file__).resolve().parent.parent

    # Load the data, a CSV previously created by `counts.py`
    df = pd.read_csv(args.infile, parse_dates=['start'])

    # Filter out desired month, if passed
    if args.month:
        df = df[df['start'].dt.month==args.month]

    # Display the cantor schedules
    if args.month:
        print(f'\nCANTOR SCHEDULE FOR {calendar.month_name[args.month].upper()}:\n')
    else:
        print('\nCANTOR SCHEDULE:\n')

    print(df[['Date', 'Mass Time', 'Name']].set_index('Date'))

    # Display cantor tallies
    print('\n')
    if args.month:
        print(f'TALLIES FOR {calendar.month_name[args.month].upper()}:\n')
    else:
        print('TALLIES:\n')
    print(df.value_counts('Name'))
    print('\n')

    # Save the cantor schedule, if desired
    if args.outfile:
        df[['Date', 'Mass Time', 'Name']].set_index('Date').to_csv(os.path.join(PROJECT_ROOT, args.outfile))
        print(f'Cantor schedule saved to file: {os.path.join(PROJECT_ROOT, args.outfile)}')

if __name__ == '__main__':
    main()